name: gitbang
description: A Git GUI frontend written in Flutter, with the goal to be simplistic and well integrated.

publish_to: 'none'

# The version may also have a build number, separated by a + symbol.
# For example, '1.0.1+7'.
version: 1.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.0.1
  flutter_launcher_icons: ^0.10.0
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "png/icon.png"
  windows:
    generate: true
    image_path: "png/icon.png"
    icon_size: 256
  linux:
    generate: true
    image_path: "png/icon.png"
    icon_size: 256

flutter:
  uses-material-design: true

  assets:
    - svg/gitbanglogo.svg